In [51]:
pip install numpy


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


# Introduction to NumPy
NumPy is a fundamental package for numerical computing in Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures.

In this notebook, we'll explore the basic usage of NumPy, including creating arrays, performing basic operations, and understanding some fundamental functions.

In [48]:
# Importing NumPy
import numpy as np

# Check the version of NumPy
print(np.__version__)

2.0.1


## Creating NumPy Arrays
NumPy arrays are similar to Python lists, but they offer better performance and more functionality. Let's create some basic arrays.

In [49]:
# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)

# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(array_2d)

# Create an array of zeros
zeros_array = np.zeros((2, 3))
print("\nArray of Zeros:")
print(zeros_array)

# Create an array of ones
ones_array = np.ones((2, 3))
print("\nArray of Ones:")
print(ones_array)

1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]

Array of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

Array of Ones:
[[1. 1. 1.]
 [1. 1. 1.]]


## Basic Operations with NumPy Arrays
NumPy arrays support a wide range of mathematical operations. We'll look at some basic operations such as addition, multiplication, and finding the mean.

In [50]:
# Basic operations
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[4, 5, 6], [7, 8, 9]])

# Addition
addition = array1 + array2
print("Addition:")
print(addition)

# Element-wise multiplication
multiplication = array1 * array2
print("\nElement-wise Multiplication:")
print(multiplication)

# Mean of array
mean_value = np.mean(array1)
print("\nMean of Array:")
print(mean_value)

Addition:
[[ 5  7  9]
 [11 13 15]]

Element-wise Multiplication:
[[ 4 10 18]
 [28 40 54]]

Mean of Array:
3.5


## Conclusion
We have covered some fundamental aspects of NumPy, including creating arrays, performing basic operations, and using common functions. NumPy is a crucial library for numerical computations and will be essential for more advanced data analysis and scientific computing tasks.